#!/bin/bash
set -e

VENV_DIR=".venv"

python3 -m venv "$VENV_DIR"
source "$VENV_DIR/bin/activate"

pip install --upgrade pip

pip install \
  mkdocs \
  mkdocs-material \
  mkdocs-enumerate-headings-plugin