site_name: microbit

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /

  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - Introduction to Microbits and variables: pages/resources/intro-variables.md
      - Functions: pages/resources/functions.md
      - Event Loop: pages/resources/event-loop.md
      - Selection: pages/resources/selection-if-else-elif.md
      - Selection in Event Loop:  pages/resources/selection-event-loop.md
      - Loops and conditions:  pages/resources/loops.md
      - DataTypes - Strings and Numbers: pages/resources/datatypes.md
      - Strings: pages/resources/strings.md
      - Lists: pages/resources/lists.md
      - File Manipulation: pages/resources/file-manipulation.md
    - Tasks:
      - Introduction to micro:bit: pages/tasks/intro-to-microbit.md
      - Variables: pages/tasks/variables.md
      - Functions: pages/tasks/functions.md
      - Functions, Parameters, and Returns: pages/tasks/functions-params-returns.md
      - Event Loop: pages/tasks/event-loop.md
      - Selection: pages/tasks/selection.md
      - Loops with Conditions: pages/tasks/loops-with-conditions.md
      - For Loops: pages/tasks/for-loops.md
      - Lists: pages/tasks/lists.md
      - File Manipulation: pages/tasks/file-manipulation.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: purple
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      restart_increment_after: 
        -  pages/tasks/intro-to-microbit.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
