site_name: AI-Assisted Development

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /

  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - What is AI-Assisted Development: pages/resources/what-is-ai-assisted-dev.md
      - AI Chatbots: pages/resources/ai-chatbots.md
      - AI Agents: pages/resources/ai-agents.md
      - Plan Mode in Agents: pages/resources/plan-mode.md
      - AGENTS.md: pages/resources/agent-project-files.md
      - Writing Effective Prompts: pages/resources/writing-effective-prompts.md
      - Optimizing Token Usage: pages/resources/optimizing-token-usage.md

    - Tasks:
      - Plan a Feature with a Chatbot: pages/tasks/plan-with-chatbot.md
      - Complete a Task with an AI Agent: pages/tasks/task-with-agent.md
      - Prompt Writing Practice: pages/tasks/prompt-writing-practice.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: cyan
  features:
    - toc.integrate
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      restart_increment_after:
        - pages/tasks/plan-with-chatbot.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
