site_name: Hardware & OS

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /
  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - Hardware:
        - Computer Hardware Components: pages/resources/hardware-components.md
        - Identifying Industry Technologies: pages/resources/identifying-industry-tech.md
        - Implementing and Evaluating Technology: pages/resources/implementing-evaluating-tech.md
        - Technology Trends and Industry Standards: pages/resources/technology-trends-and-standards.md
        - Gathering and Evaluating Technology Information: pages/resources/gathering-and-evaluating-technology-information.md
        - Workplace and Legal Requirements: pages/resources/workplace-and-legal-requirements.md
      - Raspberry Pi:
        - Raspberry Pi Zero W: pages/resources/raspberry-pi-zero-w.md
        - Using Raspberry Pi Imager: pages/resources/raspberry-pi-imager.md
        - Raspberry Pi OS Lite: pages/resources/raspberry-pi-os-lite.md
        - Configuring Wi-Fi: pages/resources/configuring-wifi.md
        - Enabling SSH: pages/resources/enabling-ssh.md
        - Using ifconfig: pages/resources/ifconfig.md
        - Listing Hardware and USB Devices: pages/resources/listing-hardware-usb-devices.md
        - Working with Text Editors: pages/resources/text-editors.md
      - Operating Systems:
        - Introduction to Operating Systems: pages/resources/intro-to-os.md
        - Hardware, Software, and Operating Systems: pages/resources/hardware-software-os.md
        - Installing an Operating System: pages/resources/installing-os.md
        - The Boot Process: pages/resources/boot-process.md
        - Interfaces — GUI and Command Line: pages/resources/gui-cli.md
        - Command Line Basics: pages/resources/command-line-basics.md
        - Managing Software and Hardware: pages/resources/managing-software-hardware.md
        - System Optimisation and Maintenance: pages/resources/system-optimisation.md
        - Optimisation Tools and Vendor Utilities: pages/resources/optimisation-tools-and-vendor-utilities.md
      - Virtual Machines:
        - Introduction to Virtual Machines: pages/resources/virtual-machines.md
        - Installing an OS in VirtualBox: pages/resources/virtualbox-installing-os.md
        - Installing an OS in VMware: pages/resources/vmware-installing-os.md
    - Tasks:
      - "Research: Hardware, OS, and Software Selection": pages/tasks/hardware-os-software-selection.md
      - "Research: Selecting Hardware for a Small Project": pages/tasks/selecting-project-hardware.md
      - Raspberry Pi:
        - Connecting to a Raspberry Pi via SSH: pages/tasks/connecting-via-ssh.md
        - Navigating the Raspberry Pi CLI: pages/tasks/cli-navigation-raspberry-pi.md
        - Installing and Managing Software on Raspberry Pi: pages/tasks/installing-software-raspberry-pi.md
        - Customising the Message of the Day (MOTD): pages/tasks/customising-motd.md
      - Creating Files and Folders on the Linux CLI: pages/tasks/creating-files-folders-cli.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: red
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      # restart_increment_after: 
      #  - path/to/page.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
