site_name: Build Simple Webpages

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /
  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - Intro to HTML: pages/resources/intro-to-html.md
      - Elements: pages/resources/elements.md
      - Nested Elements: pages/resources/nested-elements.md
      - Attributes: pages/resources/element-attributes.md
      - Tables and Forms: pages/resources/tables-forms.md
      - W3C: pages/resources/w3c.md
      - Deploying to GitHub Pages: pages/resources/deployment-github.md
      - Additional Resources: pages/resources/additional-resources.md
    - Tasks:
      - Task 1 - Elements: pages/tasks/task-1-elements.md
      - Task 2 - Nested Elements: pages/tasks/task-2-nested-elements.md
      - Task 3 - Attributes: pages/tasks/task-3-attributes.md
      - Task 4 - Tables and Forms: pages/tasks/task-4-tables-forms.md
      # - Task 5 - Links and Pages: pages/tasks/task-5-links-pages.md
      - Task 6 - Cafe Site: pages/tasks/task-6-cafe.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: teal
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      restart_increment_after: 
       - pages/tasks/task-1-elements.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
