site_name: Design

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

site_url: https://design-docs.netlify.app

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: https://robocoportal.netlify.app/

  - Design Thinking:
    - Resources:
      - 3D Printing Intro: design/resources/3d-printing-intro.md
      - FDM Printing: design/resources/fdm-printing.md
      - Design Thinking - Double Diamond: design/resources/design-thinking-double-diamond.md
      - Double Diamond - Develop and Deliver: design/resources/double-diamond-develop-deliver.md
    - Tasks:
      - Task 1 - Basic 3D Design: design/tasks/task-1-basic-tinkercad.md
      - Task 2 - Basic 3D Modeling: design/tasks/task-2-basic-modeling.md
      - Task 3 - Develop and Deliver: design/tasks/task-3-develop-deliver.md
    - Class Activities:
      - Activity 1 - Double Diamond - Discover: design/tasks/class/class-activity-1-double-diamond-discover.md
      - Activity 2 - Double Diamond - Define: design/tasks/class/class-activity-2-double-diamond-define.md
  # Add additional navigation below this point:

# Do not touch anything below this line unless you knwo what you are doing.
theme:
  name: material
  palette:
    primary: light blue
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      restart_increment_after: 
        - design/tasks/task-1-basic-tinkercad.md
        - design/tasks/class/class-activity-1-double-diamond-discover.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
