INHERIT: ../../shared/.mkdocs-base.yml

site_name: Version Control

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /

  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - What is Version Control: pages/resources/version-control/what-is-vc.md
      - Git with VS Code: pages/resources/version-control/git-in-vscode.md
      - Branching Strategy: pages/resources/version-control/branching-strategy.md
      - Git Tools and Clients: pages/resources/version-control/git-tools.md
      - What is GitHub: pages/resources/version-control/what-is-github.md
      - .gitignore: pages/resources/version-control/gitignore.md
      - Merge Conflicts: pages/resources/version-control/merge-conflicts.md

    - Tasks:
      - Git Intro Walkthrough: pages/tasks/git-intro-walkthrough.md
      - Initialise and Commit: pages/tasks/initialise-and-commit.md
      - Branch and Merge: pages/tasks/branch-and-merge.md
      - Daily Workflow: pages/tasks/daily-workflow.md
      - Working with a dev Branch: pages/tasks/working-with-dev.md
      - Pull Request Workflow: pages/tasks/pull-request-workflow.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  palette:
    primary: blue

plugins:
  - enumerate-headings:
      increment_across_pages: true
      restart_increment_after:
        - pages/tasks/git-intro-walkthrough.md
