INHERIT: ../../shared/.mkdocs-base.yml

site_name: Test Site

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: https://bki-di.pages.dev/
  - Menu:
    - Resources:
      - Markdown Elements: pages/resources/markdown-elements.md
      - Code and Callouts: pages/resources/code-and-callouts.md
    - Tasks:
      - Example Task: pages/tasks/example-task.md

  # Add additional navigation below this point:

# Do not touch anything below this line unless you know what you are doing.
theme:
  palette:
    primary: green

plugins:
  - enumerate-headings:
      increment_across_pages: true
      restart_increment_after:
        - pages/tasks/example-task.md
