site_name: Test Site

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: https://bki-di-portal.netlify.app/

  # Add additional navigation below this point:

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: green
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      # restart_increment_after: 
      #  - path/to/page.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
