site_name: NextJS

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: https://bki-di-portal.netlify.app/

  # Add additional navigation below this point:
  - NextJS:
    - Resources:
      - NextJS Introduction: pages/resources/nextjs-introduction.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  custom_dir: ../../shared
  palette:
    primary: black
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

# This is relative to the theme/base (based on custom_dir above)
extra_css:
  - style.css

# This is here to watch the style.css file above to trigger hot-reload,
# therefor if the custom_dir is changed it should be changed here too.
watch:
  - ../../shared/style.css

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      # restart_increment_after: 
      #  - path/to/page.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
